### ISSUE TITLE
Error returned during editing

### ISSUE THREAD

**Issue by TheQuantum** [tektronixofficial/vscode-tsplang#31]
### Subject of the issue
Error returned during normal editing

### Your environment
* shebang: --#!2450
* TSPLang version: 0.4.0
* VSCode version info:
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

### Steps to reproduce
Block of TSP when error was generated:
function update()
    dmm.measure.read(defbuffer1)
    local percentChange = {}
    for i = 0, (dmm.measure.count - 1) do
        percentChange[i 
    end
end

### Expected behaviour
No error

### Actual behaviour
Error returned in TSP Command Autocomplete Output:
[Error - 10:33:57 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Invalid regular expression: /percentChange[i/: Unterminated character class
  Code: -32603

**Comment by TheQuantum** [comment]
Another example: 
By typing line:
        buffer.write.reading(App_buffer, defbuffer1[e
(Attempting to type buffer.write.reading(App_buffer, defbuffer1[endindex])

Returns:
[Error - 11:06:44 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Invalid regular expression: /defbuffer1[e/: Unterminated character class
  Code: -32603

**Comment by ethall** [comment]
This is an error in line 50 of `/server/src/completionProcessor.ts` wherein I foolishly decided to use an un-escaped string variable as the text of a regular expression.

**Comment by ethall** [comment]
Resolved in [v0.4.2](/tektronixofficial/vscode-tsplang/releases/tag/v0.4.2).
